import { BlockName } from "../object/blockNames"
import { ItemName } from "../object/itemNames"

export const useItem:[BlockName,ItemName,BlockName][] = [
    //flower_pot
    ["flower_pot","acacia_sapling","potted_acacia_sapling"],
    ["flower_pot","allium","potted_allium"],
    ["flower_pot","azalea","potted_azalea_bush"],
    ["flower_pot","azure_bluet","potted_azure_bluet"],
    ["flower_pot","bamboo","potted_bamboo"],
    ["flower_pot","birch_sapling","potted_birch_sapling"],
    ["flower_pot","blue_orchid","potted_blue_orchid"],
    ["flower_pot","brown_mushroom","potted_brown_mushroom"],
    ["flower_pot","cactus","potted_cactus"],
    ["flower_pot","cherry_sapling","potted_cherry_sapling"],
    ["flower_pot","closed_eyeblossom","potted_closed_eyeblossom"],
    ["flower_pot","cornflower","potted_cornflower"],
    ["flower_pot","crimson_fungus","potted_crimson_fungus"],
    ["flower_pot","crimson_roots","potted_crimson_roots"],
    ["flower_pot","dandelion","potted_dandelion"],
    ["flower_pot","dark_oak_sapling","potted_dark_oak_sapling"],
    ["flower_pot","dead_bush","potted_dead_bush"],
    ["flower_pot","fern","potted_fern"],
    ["flower_pot","flowering_azalea","potted_flowering_azalea_bush"],
    ["flower_pot","jungle_sapling","potted_jungle_sapling"],
    ["flower_pot","lily_of_the_valley","potted_lily_of_the_valley"],
    ["flower_pot","mangrove_propagule","potted_mangrove_propagule"],
    ["flower_pot","oak_sapling","potted_oak_sapling"],
    ["flower_pot","open_eyeblossom","potted_open_eyeblossom"],
    ["flower_pot","orange_tulip","potted_orange_tulip"],
    ["flower_pot","oxeye_daisy","potted_oxeye_daisy"],
    ["flower_pot","pale_oak_sapling","potted_pale_oak_sapling"],
    ["flower_pot","pink_tulip","potted_pink_tulip"],
    ["flower_pot","poppy","potted_poppy"],
    ["flower_pot","red_mushroom","potted_red_mushroom"],
    ["flower_pot","red_tulip","potted_red_tulip"],
    ["flower_pot","spruce_sapling","potted_spruce_sapling"],
    ["flower_pot","torchflower","potted_torchflower"],
    ["flower_pot","warped_fungus","potted_warped_fungus"],
    ["flower_pot","warped_roots","potted_warped_roots"],
    ["flower_pot","white_tulip","potted_white_tulip"],
    ["flower_pot","wither_rose","potted_wither_rose"],
    //bonemeal
    ["big_dripleaf","bone_meal","big_dripleaf_stem"],
    ["cave_vines","bone_meal","cave_vines_plant"],
    //cake
    ["cake","candle","candle_cake"],
    ["cake","red_candle","red_candle_cake"],
    ["cake","blue_candle","blue_candle_cake"],
    ["cake","cyan_candle","cyan_candle_cake"],
    ["cake","gray_candle","gray_candle_cake"],
    ["cake","lime_candle","lime_candle_cake"],
    ["cake","pink_candle","pink_candle_cake"],
    ["cake","black_candle","black_candle_cake"],
    ["cake","brown_candle","brown_candle_cake"],
    ["cake","green_candle","green_candle_cake"],
    ["cake","white_candle","white_candle_cake"],
    ["cake","orange_candle","orange_candle_cake"],
    ["cake","purple_candle","purple_candle_cake"],
    ["cake","yellow_candle","yellow_candle_cake"],
    ["cake","magenta_candle","magenta_candle_cake"],
    ["cake","light_blue_candle","light_blue_candle_cake"],
    ["cake","light_gray_candle","light_gray_candle_cake"],
    
    //todo
] as const